Files already downloaded and verified
Ignoring network_output argument, using prob and logprob to obtain KL divergence
Traceback (most recent call last):
  File "validate.py", line 756, in <module>
    main()
  File "validate.py", line 653, in main
    pruning_settings_reader.read_config(args.pruning_config)
  File "/home/kduncan/Pruning/pruning_engine.py", line 52, in read_config
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './configs/CIFAR100_0_100.json'
