densenet121 model is not supported
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "main_allepsilons.py", line 1154, in <module>
    main()
  File "main_allepsilons.py", line 916, in main
    constraint = eval(args.constraint)(model, use_cuda, network_output=args.network_output)
UnboundLocalError: local variable 'model' referenced before assignment
densenet121 model is not supported
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "main_allepsilons.py", line 1154, in <module>
    main()
  File "main_allepsilons.py", line 916, in main
    constraint = eval(args.constraint)(model, use_cuda, network_output=args.network_output)
UnboundLocalError: local variable 'model' referenced before assignment
Traceback (most recent call last):
  File "remove_header.py", line 3, in <module>
    lines = open(sys.argv[1], 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '../CIFAR100_resnet50_128/log_CIFAR100_densenet121_10_30_0.01_RobustnessDandR_eps1=7.8,_eps2=2.9__FGSM.txt'
/cm/local/apps/slurm/var/spool/job204693/slurm_script: line 25: files/CIFAR100_densenet121_10_30_0.01_RobustnessDandR_eps1=7.8,_eps2=2.9__FGSM.txt: No such file or directory
Traceback (most recent call last):
  File "remove_header.py", line 3, in <module>
    lines = open(sys.argv[1], 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '../CIFAR100_resnet50_128/log_CIFAR100_densenet121_10_30_0.2_RobustnessDandR_eps1=7.8,_eps2=2.9__FGSM.txt'
