Traceback (most recent call last):
  File "test_models.py", line 792, in <module>
    main()
  File "test_models.py", line 699, in main
    with open(args.log_file,'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'process_output/text/log_CIFAR100_resnet50_350_100_0.125_RobustnessG_eps=0.3,_delta=0.52__64.txt'
Files already downloaded and verified
CIFAR100_resnet50_350_100_0.125_RobustnessG_eps=0.3,_delta=0.52__32
test_models.py --dataset=CIFAR100 --model=resnet50 --tensorboard=True --pruning_config=./configs/CIFAR100_350_100.json --constraint=RobustnessG(eps=0.3, delta=0.52) --dl2-weight=0.125 --batch-size=32 --name=CIFAR100_res_64_final --checkpoint_folder=CIFAR100_res_64 --log_file=process_output/text/log_CIFAR100_resnet50_350_100_0.125_RobustnessG_eps=0.3,_delta=0.52__64.txt
